### ISSUE TITLE
Action needed to work along with sherlock lib

### ISSUE THREAD

**Issue by ktamilselvan1** [maurycyw/StaggeredGridView#18]
Your lip is really nice.,
i tried to use this.
since i used sherlock and sliding menu lib for slidingmenu and actionbar components.,i cannot use your lib to get StaggeredGridView. giving "Jar Mismatch error" for that jar "Android support lib v4" you had used..

May i know the reason and how can i use your lib?

**Comment by adhiravishankar** [comment]
I had that same problem with another library. Just delete the android support jar for staggeredgridview, but link the staggeredgridview to use the android support jar from actionbarsherlock. What I do is delete every support jar that I get in every library I use, and link it all to a support jar that is updated, because many of the support jars are not updated, especially ActionBarSherlock, in these libraries, and it is best to use the latest support jar.

**Comment by maurycyw** [comment]
adhiravishankar is correct... the support libraries are just not the same version across all of your various libs. You could either make them all identical or link of your libraries to a single support jar.
