### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by BenMoment** [maurycyw/StaggeredGridView#9]
Hi. Appreciate your work. Do you think there should be an easy way of adding a footer view to the grid? Been trying to think of one.

**Comment by maurycyw** [comment]
Well I believe ListView keeps track of the header and footer views in two separate ArrayList's via a FixedViewInfo class. If any headers or footers exist it wraps the adapter in a HeaderViewListAdapter. From what I can tell recycling seems to be mostly what StaggeredGridView would need to worry about otherwise it should be fairly simple to implement ( I am going to probably regret saying this ). 

If you manage to implement this then please send a pull request my way. This seems like a fun problem to solve so if you cant figure this one out I will take a look once I manage to find some free time.

**Comment by briangriffey** [comment]
@BenMoment  Since the regular GridVIew does not support a header and footer, I don't believe the StaggeredGridView should support one either.  Thoughts? @vinc3m1 @maurycyw

**Comment by vinc3m1** [comment]
I agree for now. If there's a nice and clean implementation, I'm all for it, but until then...

**Comment by briangriffey** [comment]
Cool, then I'll close for now.
